/// <reference types="cypress" />

describe("user-story", () => {


    var environment = Cypress.env("domain_baseurl")

    or

    //cy.get (Cypress.env("domain_baseurl")

    it('choose item', { tags: ['smoke'] }, () => {
        cy.visit("https://automationexercise.com/")
        cy.get('ul.nav-justified a').eq(0).trigger("mouseover")
        cy.get('ul.nav-justified a').eq(0).click()
        cy.url().should("contain", "/product_details/1")
        cy.contains("h2", "Blue Top")
    })
    it('Write review', () => {
        cy.visit("https://automationexercise.com/product_details/1")
        cy.get("#name").type("Mike")
        cy.get("#email").type("Mike@test.com")
        cy.get("#review").type("Thank  you for good top, my wife very happy!")
        cy.get('#button-review').trigger("mouseover")
        cy.get('#button-review').click()
        cy.contains('span', 'Thank you for your review.')
    })
})
//     it('Work with item', () => {
//         cy.visit("https://automationexercise.com/product_details/1")
//         cy.get('#quantity')
//             .clear()
//             .type('3')
//         cy.contains('button', 'Add to cart').click()
//         cy.get('button[data-dismiss="modal"]').click()
//         cy.visit("https://automationexercise.com/view_cart")
//         cy.contains("h4", "Blue Top").should("be.visible")
//         cy.contains('a', 'Proceed To Checkout').click()
//         cy.contains('u', 'Register / Login').click()
//         cy.url().should("contain", "/login")
//         cy.get('[data-qa="login-email"]')
//             .should('be.visible')
//             .type("ivan30@gmail.com")
//         cy.get('[data-qa="login-password"]')
//             .should('be.visible')
//             .type("112233")
//         cy.get('[data-qa="login-button]')
//             .should('be.visible')
//             .click()
//         cy.visit("https://automationexercise.com/view_cart")
//         cy.contains("h4", "Blue Top").should("be.visible")
//         cy.contains('a', 'Proceed To Checkout').click()
//         cy.url().should("contain", "/checkout")
//         cy.get('a[href="/payment"]').click()
//         cy.url().should("contain", "/payment")
//         cy.get('input[data-qa="name-on-card"]').type("VISA")
//         cy.get('input[data-qa="card-number"]').type("9123873476451260")
//         cy.get('input[data-qa="cvc"]').type("2312")
//         cy.get('input[data-qa="expiry-month"]').type("7675")
//         cy.get('input[data-qa="expiry-year"]').type("agree")
//         cy.get('button[data-qa="pay-button"]').click()
//         cy.url().should("contain", "/payment_done/1500")
//         cy.contains('p', 'Congratulations! Your order has been confirmed!')
//     })
// })