name: Cypress Tests

on:
  push:
    branches: [ main, master ]  # Запускать на пуш в ветки main или master

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Можно поставить свою версию Node.js

      - name: Install dependencies
        run: npm ci  # Быстрая и чистая установка из package-lock.json

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6